USE clinica_diabetes;

ALTER TABLE consulta_medicina_interna
-- Radiología
ADD COLUMN prox_rad_craneo TINYINT(1) DEFAULT 0,
ADD COLUMN prox_rad_senos TINYINT(1) DEFAULT 0,
ADD COLUMN prox_rad_perfilograma TINYINT(1) DEFAULT 0,
ADD COLUMN prox_rad_cuello TINYINT(1) DEFAULT 0,
ADD COLUMN prox_rad_col_cervical TINYINT(1) DEFAULT 0,
ADD COLUMN prox_rad_col_dorsal TINYINT(1) DEFAULT 0,
ADD COLUMN prox_rad_col_lumbar TINYINT(1) DEFAULT 0,
ADD COLUMN prox_rad_col_oblicuas TINYINT(1) DEFAULT 0,
ADD COLUMN prox_rad_col_oblicuas_desc VARCHAR(100) DEFAULT NULL,
ADD COLUMN prox_rad_col_dinamicas TINYINT(1) DEFAULT 0,
ADD COLUMN prox_rad_col_dinamicas_desc VARCHAR(100) DEFAULT NULL,
ADD COLUMN prox_rad_torax_pa TINYINT(1) DEFAULT 0,
ADD COLUMN prox_rad_torax_lat TINYINT(1) DEFAULT 0,
ADD COLUMN prox_rad_torax_oseo_ap TINYINT(1) DEFAULT 0,
ADD COLUMN prox_rad_torax_oseo_obl TINYINT(1) DEFAULT 0,
ADD COLUMN prox_rad_abd_supino TINYINT(1) DEFAULT 0,
ADD COLUMN prox_rad_abd_bipe TINYINT(1) DEFAULT 0,
ADD COLUMN prox_rad_escanometria TINYINT(1) DEFAULT 0,
ADD COLUMN prox_rad_huesos TINYINT(1) DEFAULT 0,
ADD COLUMN prox_rad_huesos_desc VARCHAR(100) DEFAULT NULL,
ADD COLUMN prox_rad_cefalopelvi TINYINT(1) DEFAULT 0,

-- Estudios Contrastados
ADD COLUMN prox_con_esofagograma TINYINT(1) DEFAULT 0,
ADD COLUMN prox_con_serie_egd TINYINT(1) DEFAULT 0,
ADD COLUMN prox_con_transito_int TINYINT(1) DEFAULT 0,
ADD COLUMN prox_con_colon_enema TINYINT(1) DEFAULT 0,
ADD COLUMN prox_con_colangio_t TINYINT(1) DEFAULT 0,
ADD COLUMN prox_con_urograma TINYINT(1) DEFAULT 0,
ADD COLUMN prox_con_cistograma TINYINT(1) DEFAULT 0,
ADD COLUMN prox_con_uretrograma TINYINT(1) DEFAULT 0,

-- Ultrasonido
ADD COLUMN prox_us_abd_completo TINYINT(1) DEFAULT 0,
ADD COLUMN prox_us_higado_vias TINYINT(1) DEFAULT 0,
ADD COLUMN prox_us_renal_vias TINYINT(1) DEFAULT 0,
ADD COLUMN prox_us_pelvico_gin TINYINT(1) DEFAULT 0,
ADD COLUMN prox_us_gin_endovag TINYINT(1) DEFAULT 0,
ADD COLUMN prox_us_prostatico TINYINT(1) DEFAULT 0,
ADD COLUMN prox_us_pros_transrectal TINYINT(1) DEFAULT 0,
ADD COLUMN prox_us_testicular TINYINT(1) DEFAULT 0,
ADD COLUMN prox_us_inguinal TINYINT(1) DEFAULT 0,
ADD COLUMN prox_us_cuello_tiroides TINYINT(1) DEFAULT 0,
ADD COLUMN prox_us_transfontanelar TINYINT(1) DEFAULT 0,
ADD COLUMN prox_us_obstetrico TINYINT(1) DEFAULT 0,
ADD COLUMN prox_us_obstetrico_4d TINYINT(1) DEFAULT 0,
ADD COLUMN prox_us_obstetrico_doppler TINYINT(1) DEFAULT 0,
ADD COLUMN prox_us_perfil_biofisico TINYINT(1) DEFAULT 0,
ADD COLUMN prox_us_doppler_obs TINYINT(1) DEFAULT 0,
ADD COLUMN prox_us_doppler_carotida TINYINT(1) DEFAULT 0,
ADD COLUMN prox_us_doppler_venoso_art TINYINT(1) DEFAULT 0,
ADD COLUMN prox_us_doppler_ext_venoso_art TINYINT(1) DEFAULT 0,
ADD COLUMN prox_us_doppler_abd_renal TINYINT(1) DEFAULT 0,
ADD COLUMN prox_us_doppler_testicular TINYINT(1) DEFAULT 0,
ADD COLUMN prox_us_mamario TINYINT(1) DEFAULT 0,
ADD COLUMN prox_us_tejidos_blandos TINYINT(1) DEFAULT 0,
ADD COLUMN prox_us_musculoesqueletico TINYINT(1) DEFAULT 0,
ADD COLUMN prox_us_prueba_boyden TINYINT(1) DEFAULT 0,
ADD COLUMN prox_us_seguimientos_foli TINYINT(1) DEFAULT 0,

-- Tomografía
ADD COLUMN prox_tac_craneo TINYINT(1) DEFAULT 0,
ADD COLUMN prox_tac_silla_turca TINYINT(1) DEFAULT 0,
ADD COLUMN prox_tac_senos TINYINT(1) DEFAULT 0,
ADD COLUMN prox_tac_orbitas_oidos TINYINT(1) DEFAULT 0,
ADD COLUMN prox_tac_macizo_3d TINYINT(1) DEFAULT 0,
ADD COLUMN prox_tac_cuello TINYINT(1) DEFAULT 0,
ADD COLUMN prox_tac_col_cervical TINYINT(1) DEFAULT 0,
ADD COLUMN prox_tac_col_dorsal TINYINT(1) DEFAULT 0,
ADD COLUMN prox_tac_col_lumbar TINYINT(1) DEFAULT 0,
ADD COLUMN prox_tac_torax_ar TINYINT(1) DEFAULT 0,
ADD COLUMN prox_tac_abdominopelvica TINYINT(1) DEFAULT 0,
ADD COLUMN prox_tac_toracoabdominopelvica TINYINT(1) DEFAULT 0,
ADD COLUMN prox_tac_urotac TINYINT(1) DEFAULT 0,
ADD COLUMN prox_tac_cadera_3d TINYINT(1) DEFAULT 0,
ADD COLUMN prox_tac_hombro TINYINT(1) DEFAULT 0,
ADD COLUMN prox_tac_codo TINYINT(1) DEFAULT 0,
ADD COLUMN prox_tac_muneca TINYINT(1) DEFAULT 0,
ADD COLUMN prox_tac_rodilla TINYINT(1) DEFAULT 0,
ADD COLUMN prox_tac_tobillo TINYINT(1) DEFAULT 0,
ADD COLUMN prox_tac_otra VARCHAR(100) DEFAULT NULL,
ADD COLUMN prox_tac_angio_carotidas TINYINT(1) DEFAULT 0,
ADD COLUMN prox_tac_angio_aorta TINYINT(1) DEFAULT 0,
ADD COLUMN prox_tac_angio_pulmonar TINYINT(1) DEFAULT 0,
ADD COLUMN prox_tac_angio_abdominal TINYINT(1) DEFAULT 0,
ADD COLUMN prox_tac_angio_renal TINYINT(1) DEFAULT 0,
ADD COLUMN prox_tac_angio_ext_sup TINYINT(1) DEFAULT 0,
ADD COLUMN prox_tac_angio_ext_inf TINYINT(1) DEFAULT 0,
ADD COLUMN prox_tac_simple TINYINT(1) DEFAULT 0,
ADD COLUMN prox_tac_contraste TINYINT(1) DEFAULT 0;
