USE clinica_diabetes;

ALTER TABLE consulta_medicina_interna
ADD COLUMN IF NOT EXISTS prox_bh TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_osc TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_ego TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_hba1c TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_perfil_tiroideo TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_perfil_hepatico TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_insulina_basal TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_qs3_i TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_qs3_ii TINYINT(1) DEFAULT 0;
