-- Migración para el rediseño de Medicina Interna
-- Agregando campos detallados para medicación, laboratorios y complicaciones

ALTER TABLE consulta_medicina_interna
-- Medicación: Antidiabéticos Orales
ADD COLUMN med_sulfonilureas_glibenclamida TINYINT(1) DEFAULT 0,
ADD COLUMN med_sulfonilureas_glimepirida TINYINT(1) DEFAULT 0,
ADD COLUMN med_sulfonilureas_gliclazida TINYINT(1) DEFAULT 0,
ADD COLUMN med_meglitinidas_repaglinida TINYINT(1) DEFAULT 0,
ADD COLUMN med_meglitinidas_nateglinida TINYINT(1) DEFAULT 0,
ADD COLUMN med_inhibidores_alfaglucosidasa_acarbosa TINYINT(1) DEFAULT 0,
ADD COLUMN med_inhibidores_alfaglucosidasa_miglitol TINYINT(1) DEFAULT 0,
ADD COLUMN med_tiazolidinedionas_pioglitazona TINYINT(1) DEFAULT 0,
ADD COLUMN med_tiazolidinedionas_rosiglitazona TINYINT(1) DEFAULT 0,

-- Antidiabéticos Nueva Generación
ADD COLUMN med_inhibidores_dpp4_sitagliptina TINYINT(1) DEFAULT 0,
ADD COLUMN med_inhibidores_dpp4_saxaglipina TINYINT(1) DEFAULT 0,
ADD COLUMN med_inhibidores_dpp4_linagliptina TINYINT(1) DEFAULT 0,
ADD COLUMN med_inhibidores_dpp4_alogliptina TINYINT(1) DEFAULT 0,
ADD COLUMN med_agonistas_glp1_exenatida TINYINT(1) DEFAULT 0,
ADD COLUMN med_agonistas_glp1_liraglutida TINYINT(1) DEFAULT 0,
ADD COLUMN med_agonistas_glp1_dulaglutida TINYINT(1) DEFAULT 0,
ADD COLUMN med_agonistas_glp1_lixisenatida TINYINT(1) DEFAULT 0,
ADD COLUMN med_agonistas_glp1_semaglutida TINYINT(1) DEFAULT 0,
ADD COLUMN med_inhibidores_sglt2_empagliflozina TINYINT(1) DEFAULT 0,
ADD COLUMN med_inhibidores_sglt2_dapagliflozina TINYINT(1) DEFAULT 0,
ADD COLUMN med_inhibidores_sglt2_canagliflozina TINYINT(1) DEFAULT 0,
ADD COLUMN med_inhibidores_sglt2_ertugliflozina TINYINT(1) DEFAULT 0,

-- Insulinas
ADD COLUMN ins_rapida_regular TINYINT(1) DEFAULT 0,
ADD COLUMN ins_ultrarrapida_lispro TINYINT(1) DEFAULT 0,
ADD COLUMN ins_ultrarrapida_aspart TINYINT(1) DEFAULT 0,
ADD COLUMN ins_ultrarrapida_glulisina TINYINT(1) DEFAULT 0,
ADD COLUMN ins_intermedia_nph TINYINT(1) DEFAULT 0,
ADD COLUMN ins_prolongada_glargina TINYINT(1) DEFAULT 0,
ADD COLUMN ins_prolongada_detemir TINYINT(1) DEFAULT 0,
ADD COLUMN ins_prolongada_degludec TINYINT(1) DEFAULT 0,
ADD COLUMN ins_ultralarga_degludec TINYINT(1) DEFAULT 0,
ADD COLUMN ins_ultralarga_glargina_u300 TINYINT(1) DEFAULT 0,
ADD COLUMN ins_mezcla_nph_regular TINYINT(1) DEFAULT 0,
ADD COLUMN ins_mezcla_lispro TINYINT(1) DEFAULT 0,
ADD COLUMN ins_mezcla_aspart TINYINT(1) DEFAULT 0,

-- Laboratorios (Verificación de realizados/revisados)
ADD COLUMN lab_glucosa_ayunas TINYINT(1) DEFAULT 0,
ADD COLUMN lab_glucosa_postprandial TINYINT(1) DEFAULT 0,
ADD COLUMN lab_curva_tolerancia TINYINT(1) DEFAULT 0,
ADD COLUMN lab_creatinina_serica TINYINT(1) DEFAULT 0,
ADD COLUMN lab_tfg TINYINT(1) DEFAULT 0,
ADD COLUMN lab_urea_bun TINYINT(1) DEFAULT 0,
ADD COLUMN lab_microalbuminuria_orina TINYINT(1) DEFAULT 0,
ADD COLUMN lab_relacion_acr TINYINT(1) DEFAULT 0,
ADD COLUMN lab_colesterol_total TINYINT(1) DEFAULT 0,
ADD COLUMN lab_ldl TINYINT(1) DEFAULT 0,
ADD COLUMN lab_hdl TINYINT(1) DEFAULT 0,
ADD COLUMN lab_trigliceridos TINYINT(1) DEFAULT 0,
ADD COLUMN lab_sodio TINYINT(1) DEFAULT 0,
ADD COLUMN lab_potasio TINYINT(1) DEFAULT 0,
ADD COLUMN lab_cloro TINYINT(1) DEFAULT 0,
ADD COLUMN lab_bicarbonato TINYINT(1) DEFAULT 0,
ADD COLUMN lab_calcio TINYINT(1) DEFAULT 0,
ADD COLUMN lab_fosforo TINYINT(1) DEFAULT 0,
ADD COLUMN lab_magnesio TINYINT(1) DEFAULT 0,
ADD COLUMN lab_gasometria TINYINT(1) DEFAULT 0,
ADD COLUMN lab_alt TINYINT(1) DEFAULT 0,
ADD COLUMN lab_ast TINYINT(1) DEFAULT 0,
ADD COLUMN lab_fosfatasa_alcalina TINYINT(1) DEFAULT 0,
ADD COLUMN lab_bilirrubinas TINYINT(1) DEFAULT 0,
ADD COLUMN lab_albumina_serica TINYINT(1) DEFAULT 0,
ADD COLUMN lab_cetonas TINYINT(1) DEFAULT 0,
ADD COLUMN lab_peptido_c TINYINT(1) DEFAULT 0,
ADD COLUMN lab_insulinemia TINYINT(1) DEFAULT 0,
ADD COLUMN lab_pcr TINYINT(1) DEFAULT 0,
ADD COLUMN lab_vsg TINYINT(1) DEFAULT 0,
ADD COLUMN lab_troponina TINYINT(1) DEFAULT 0,
ADD COLUMN lab_bnp TINYINT(1) DEFAULT 0,
ADD COLUMN lab_homocisteina TINYINT(1) DEFAULT 0,
ADD COLUMN lab_vitamina_d TINYINT(1) DEFAULT 0,
ADD COLUMN lab_hormonas_tiroideas TINYINT(1) DEFAULT 0,
ADD COLUMN lab_hemograma TINYINT(1) DEFAULT 0,

-- Control de Diabetes y Revisiones
ADD COLUMN control_hba1c_reciente_valor VARCHAR(50),
ADD COLUMN control_bitacora TINYINT(1) DEFAULT 0,
ADD COLUMN control_hipoglucemias TINYINT(1) DEFAULT 0,
ADD COLUMN control_hipoglucemias_detalles TEXT,
ADD COLUMN control_hiperglucemias_sintomaticas TINYINT(1) DEFAULT 0,
ADD COLUMN control_adherencia TINYINT(1) DEFAULT 0,
ADD COLUMN control_problemas_medicamentos TEXT,
ADD COLUMN control_tecnica_insulina TINYINT(1) DEFAULT 0,
ADD COLUMN control_glucemia_hb1ac_reciente TINYINT(1) DEFAULT 0,
ADD COLUMN control_glucemia_glucometrias_diarias TINYINT(1) DEFAULT 0,
ADD COLUMN control_glucemia_hipoglucemias_recientes TINYINT(1) DEFAULT 0,
ADD COLUMN control_glucemia_hiperglucemias_sintomaticas TINYINT(1) DEFAULT 0,
ADD COLUMN control_glucemia_cambios_medicamentos TINYINT(1) DEFAULT 0,
ADD COLUMN control_glucemia_aplicacion_insulina_adecuada TINYINT(1) DEFAULT 0,

-- Revisiones por sistema
ADD COLUMN rev_pies_detalles TEXT,
ADD COLUMN rev_neuropatia_monofilamento TINYINT(1) DEFAULT 0,
ADD COLUMN rev_renal_laboratorios TINYINT(1) DEFAULT 0,
ADD COLUMN rev_vision_borrosa TINYINT(1) DEFAULT 0,
ADD COLUMN rev_macro_coronaria TINYINT(1) DEFAULT 0,
ADD COLUMN rev_macro_claudicacion TINYINT(1) DEFAULT 0,
ADD COLUMN rev_riesgo_cv TINYINT(1) DEFAULT 0,
ADD COLUMN med_revision_completa TINYINT(1) DEFAULT 0,
ADD COLUMN med_ajuste_orales TINYINT(1) DEFAULT 0,
ADD COLUMN med_ajuste_insulina TINYINT(1) DEFAULT 0,
ADD COLUMN med_ajuste_estatina_hta TINYINT(1) DEFAULT 0,
ADD COLUMN med_evaluar_cambio TINYINT(1) DEFAULT 0,
ADD COLUMN prog_estudios_pendientes TINYINT(1) DEFAULT 0;
