-- Add all Próximos Estudios columns to consulta_medicina_interna
ALTER TABLE consulta_medicina_interna
-- Perfil Glucémico
ADD COLUMN IF NOT EXISTS prox_glucosa_ayunas TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_glucosa_postprandial TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_curva_tolerancia TINYINT(1) DEFAULT 0,
-- Perfil Renal
ADD COLUMN IF NOT EXISTS prox_creatinina TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_tfg TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_urea_bun TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_microalbuminuria TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_acr TINYINT(1) DEFAULT 0,
-- Perfil Lipídico
ADD COLUMN IF NOT EXISTS prox_colesterol_total TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_colesterol_ldl TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_colesterol_hdl TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_trigliceridos TINYINT(1) DEFAULT 0,
-- Electrolitos y Gasometría
ADD COLUMN IF NOT EXISTS prox_sodio TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_potasio TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_cloro TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_bicarbonato TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_calcio TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_fosforo TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_magnesio TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_gasometria TINYINT(1) DEFAULT 0,
-- Función Hepática / Pancreática
ADD COLUMN IF NOT EXISTS prox_alt_gpt TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_ast_got TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_fosfatasa_alcalina TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_bilirrubinas TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_albumina_serica TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_cetonas TINYINT(1) DEFAULT 0,
-- Marcadores y Otros
ADD COLUMN IF NOT EXISTS prox_pcr TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_vsg TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_peptido_c TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_insulinemia TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_vitamina_d TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_troponina TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_bnp TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prox_homocisteina TINYINT(1) DEFAULT 0;
